name: Build docker images

on:
  push:
    paths:
      - 'scripts/'
      - 'Dockerfile'
      - 'Makefile'
    branches: 
      - master

jobs:
  docker:
    name: Build and push docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup docker buildx
        uses: crazy-max/ghaction-docker-buildx@v1.6.1
        with:
          buildx-version: v0.4.1
          qemu-version: 4.2.0-7
      
      - name: Build docker image
        run: |
          git tag --list
          make docker-build-all

      - name: Push docker image into registry
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login docker.io --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          make docker-push-all
