name: Build a new version and push docker images

on:
  create:
    tags:
      - v*

jobs:
  docker:
    name: Build and push docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project and fetch all tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        run: make docker-build-all

      - name: Push docker image into registry
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login docker.io --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          make docker-push-all
